import angular from 'angular';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';
import 'angular-ui-router';
import 'angular-animate';
import 'angular-aria';
import 'angular-material';
import 'AngularDevise';

// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionaity
import './app/index';
import './layout/index';
import './identification';
import './notfound';
import './board';
import './discover';
import './photo';
import './game';
import './app';
import './services';


// Create and bootstrap application
const requires = [
  'ui.router',
  'templates',
  'ngMaterial',
  'ngAnimate',
    'Devise',
  'app.identification',
  'app.photo',
  'app.board',
  'app.discover',
  'app.notfound',
  'app.game',
  'app.layout',
  'app.landing',
  'app.services',
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
  strictDi: true
});
